### ISSUE TITLE
mongosql_auth plugin not passing credentials when using GSSAPI

### ISSUE THREAD

**Issue by baburajpb** [mongodb/mongosql-auth-c#3]
When trying to connect using MySQL client 
`mysql -u "FOO@LDAP.FOO.COM" --plugin-dir=c:\mysql\lib --default-auth=mongosql_auth -p`

Returns `Unknown MySQL Error` instead of connecting.

Same user can successfully connect to MongoDB using shell
`mongo.exe mongo.foo.com:37027/reports  --username FOO@LDAP.FOO.COM --authenticationMechanism GSSAPI --authenticationDatabase $external --gssapiServiceName mongodb --ssl`

mongosqld configuration for mongosqld version 2.5
```
systemLog:
  logAppend: true
  path: "mongosqld.log"
  verbosity: 2

security:
  enabled: true
  defaultMechanism: GSSAPI
  defaultSource: $external
  gssapi:
    serviceName: mongosql
    hostname: localhost

mongodb:
  net:
    uri: "mongo.foo.com:37027"
    ssl:
      enabled: true
    auth:
      username: FOO@LDAP.FOO.COM
      mechanism: GSSAPI
      gssapiServiceName: mongodb

net:
  bindIp: localhost
  port: 3306
  ssl:
    mode: allowSSL
    allowInvalidCertificates: true
    PEMKeyFile: mongosqld-server.pem

schema:
  sample:
    namespaces: "Reports.*"

processManagement:
  service:
    name: mongosqld
    displayName: mongosqld
    description: "MongoDB BI Connector"
```

mongo.log 
`Unauthorized: not authorized on admin to execute command { currentOp: 1, $or: [ { client: { $in: [ "10.67.196.250:51662", "10.67.196.250:51659" ] } }, { command.$client.mongos.client: { $in: [ "10.67.196.250:51662", "10.67.196.250:51659" ] } } ] }`

mongosqld.log:
```
2018-05-23T22:42:05.217-0500 E NETWORK    [conn11] write packet error: connection closed
2018-05-23T22:42:05.217-0500 E NETWORK    [conn11] handshake error: failed reading auth more data response: EOF
```

User has following roles

```
"roles" : [
        {
                "role" : "userAdminAnyDatabase",
                "db" : "admin"
        },
        {
                "role" : "root",
                "db" : "admin"
        }
]
```
